<?php

namespace Database\Seeders;

use App\Models\Asset;
use Illuminate\Database\Seeder;

class AssetSeeder extends Seeder
{
    public function run()
    {
        $this->command->info('Seeding investable assets...');

        $assets = [
            // E-Kekes (Electric Tricycles)
            [
                'asset_id' => 'EK-2024-001',
                'type' => 'vehicle',
                'model' => 'E-Keke Standard',
                'status' => 'active',
                'soh' => 95,
                'swaps' => 450,
                'location' => 'Lagos - Ikeja',
                'original_value' => 850000.00,
                'current_value' => 820000.00,
                'daily_swaps' => 8,
                'is_tokenized' => true,
                'token_id' => 'TKN-EK001',
                'total_ownership_sold' => 35.00,
                'min_investment' => 10000.00,
                'expected_roi' => 28.50,
                'risk_level' => 'low',
            ],
            [
                'asset_id' => 'EK-2024-002',
                'type' => 'vehicle',
                'model' => 'E-Keke Premium',
                'status' => 'active',
                'soh' => 98,
                'swaps' => 280,
                'location' => 'Lagos - Victoria Island',
                'original_value' => 1200000.00,
                'current_value' => 1180000.00,
                'daily_swaps' => 12,
                'is_tokenized' => true,
                'token_id' => 'TKN-EK002',
                'total_ownership_sold' => 20.00,
                'min_investment' => 15000.00,
                'expected_roi' => 32.00,
                'risk_level' => 'low',
            ],
            [
                'asset_id' => 'EK-2024-003',
                'type' => 'vehicle',
                'model' => 'E-Keke Standard',
                'status' => 'active',
                'soh' => 88,
                'swaps' => 680,
                'location' => 'Abuja - Wuse',
                'original_value' => 850000.00,
                'current_value' => 765000.00,
                'daily_swaps' => 6,
                'is_tokenized' => true,
                'token_id' => 'TKN-EK003',
                'total_ownership_sold' => 55.00,
                'min_investment' => 8000.00,
                'expected_roi' => 24.00,
                'risk_level' => 'medium',
            ],
            [
                'asset_id' => 'EK-2024-004',
                'type' => 'vehicle',
                'model' => 'E-Keke Cargo',
                'status' => 'active',
                'soh' => 92,
                'swaps' => 520,
                'location' => 'Port Harcourt',
                'original_value' => 1100000.00,
                'current_value' => 1050000.00,
                'daily_swaps' => 10,
                'is_tokenized' => true,
                'token_id' => 'TKN-EK004',
                'total_ownership_sold' => 15.00,
                'min_investment' => 12000.00,
                'expected_roi' => 30.00,
                'risk_level' => 'low',
            ],

            // Batteries
            [
                'asset_id' => 'BAT-2024-001',
                'type' => 'battery',
                'model' => 'LiFePO4 60V 100Ah',
                'status' => 'active',
                'soh' => 97,
                'swaps' => 1200,
                'location' => 'Lagos Hub - Ikeja',
                'original_value' => 450000.00,
                'current_value' => 440000.00,
                'daily_swaps' => 4,
                'is_tokenized' => true,
                'token_id' => 'TKN-BAT001',
                'total_ownership_sold' => 40.00,
                'min_investment' => 5000.00,
                'expected_roi' => 35.00,
                'risk_level' => 'low',
            ],
            [
                'asset_id' => 'BAT-2024-002',
                'type' => 'battery',
                'model' => 'LiFePO4 72V 120Ah',
                'status' => 'active',
                'soh' => 94,
                'swaps' => 1850,
                'location' => 'Lagos Hub - Lekki',
                'original_value' => 580000.00,
                'current_value' => 545000.00,
                'daily_swaps' => 6,
                'is_tokenized' => true,
                'token_id' => 'TKN-BAT002',
                'total_ownership_sold' => 25.00,
                'min_investment' => 6000.00,
                'expected_roi' => 38.00,
                'risk_level' => 'medium',
            ],
            [
                'asset_id' => 'BAT-2024-003',
                'type' => 'battery',
                'model' => 'LiFePO4 60V 100Ah',
                'status' => 'active',
                'soh' => 91,
                'swaps' => 2100,
                'location' => 'Abuja Hub',
                'original_value' => 450000.00,
                'current_value' => 405000.00,
                'daily_swaps' => 5,
                'is_tokenized' => true,
                'token_id' => 'TKN-BAT003',
                'total_ownership_sold' => 60.00,
                'min_investment' => 4500.00,
                'expected_roi' => 32.00,
                'risk_level' => 'medium',
            ],

            // Charging Cabinets
            [
                'asset_id' => 'CAB-2024-001',
                'type' => 'charging_cabinet',
                'model' => '8-Slot Fast Charger',
                'status' => 'active',
                'soh' => 100,
                'swaps' => 3500,
                'location' => 'Lagos - Ikeja Station',
                'original_value' => 2500000.00,
                'current_value' => 2450000.00,
                'daily_swaps' => 45,
                'is_tokenized' => true,
                'token_id' => 'TKN-CAB001',
                'total_ownership_sold' => 10.00,
                'min_investment' => 25000.00,
                'expected_roi' => 42.00,
                'risk_level' => 'low',
            ],
            [
                'asset_id' => 'CAB-2024-002',
                'type' => 'charging_cabinet',
                'model' => '12-Slot Fast Charger',
                'status' => 'active',
                'soh' => 98,
                'swaps' => 5200,
                'location' => 'Lagos - Lekki Station',
                'original_value' => 3500000.00,
                'current_value' => 3400000.00,
                'daily_swaps' => 60,
                'is_tokenized' => true,
                'token_id' => 'TKN-CAB002',
                'total_ownership_sold' => 5.00,
                'min_investment' => 35000.00,
                'expected_roi' => 45.00,
                'risk_level' => 'low',
            ],
            [
                'asset_id' => 'CAB-2024-003',
                'type' => 'charging_cabinet',
                'model' => '8-Slot Fast Charger',
                'status' => 'active',
                'soh' => 96,
                'swaps' => 4100,
                'location' => 'Abuja - Central Station',
                'original_value' => 2500000.00,
                'current_value' => 2380000.00,
                'daily_swaps' => 40,
                'is_tokenized' => true,
                'token_id' => 'TKN-CAB003',
                'total_ownership_sold' => 30.00,
                'min_investment' => 20000.00,
                'expected_roi' => 40.00,
                'risk_level' => 'low',
            ],

            // More vehicles for variety
            [
                'asset_id' => 'EK-2024-005',
                'type' => 'vehicle',
                'model' => 'E-Keke Deluxe',
                'status' => 'active',
                'soh' => 99,
                'swaps' => 120,
                'location' => 'Lagos - Surulere',
                'original_value' => 1500000.00,
                'current_value' => 1490000.00,
                'daily_swaps' => 14,
                'is_tokenized' => true,
                'token_id' => 'TKN-EK005',
                'total_ownership_sold' => 0.00,
                'min_investment' => 20000.00,
                'expected_roi' => 35.00,
                'risk_level' => 'low',
            ],
            [
                'asset_id' => 'EK-2024-006',
                'type' => 'vehicle',
                'model' => 'E-Keke Standard',
                'status' => 'active',
                'soh' => 85,
                'swaps' => 890,
                'location' => 'Kano',
                'original_value' => 850000.00,
                'current_value' => 680000.00,
                'daily_swaps' => 5,
                'is_tokenized' => true,
                'token_id' => 'TKN-EK006',
                'total_ownership_sold' => 75.00,
                'min_investment' => 5000.00,
                'expected_roi' => 20.00,
                'risk_level' => 'medium',
            ],
        ];

        foreach ($assets as $assetData) {
            Asset::updateOrCreate(
                ['asset_id' => $assetData['asset_id']],
                $assetData
            );
        }

        $this->command->info('Created ' . count($assets) . ' investable assets');
    }
}
