@extends('emails.layout')

@section('title', 'Dividend Payout - FleetFi')

@section('content')
<h2>Dividend Payout Received!</h2>

<p>Dear {{ $userName }},</p>

<div class="success-box">
    <strong>Great news!</strong><br>
    Your dividend payout for {{ $period }} has been credited to your FleetFi wallet.
</div>

<div style="text-align: center; background-color: #e8f4fd; padding: 30px; border-radius: 8px; margin: 20px 0;">
    <p style="margin: 0; font-size: 14px; color: #666;">Amount Credited</p>
    <p style="margin: 10px 0; font-size: 36px; font-weight: 700; color: #1a73e8;">&#8358;{{ $amount }}</p>
    <p style="margin: 0; font-size: 12px; color: #999;">For period: {{ $period }}</p>
</div>

<h3>Payout Breakdown</h3>
<p>
    This payout represents your share of the fleet revenue generated during {{ $period }}.
    Your earnings are calculated based on:
</p>
<ul>
    <li>Your ownership percentage of each asset</li>
    <li>Total revenue generated by your assets</li>
    <li>Operational costs deductions</li>
    <li>Platform management fees</li>
</ul>

<h3>What You Can Do</h3>
<ul>
    <li><strong>Reinvest:</strong> Grow your portfolio by investing in more EV assets</li>
    <li><strong>Withdraw:</strong> Transfer funds to your bank account</li>
    <li><strong>Hold:</strong> Keep funds in your wallet for future investments</li>
</ul>

<div style="text-align: center; margin: 30px 0;">
    <a href="{{ $walletUrl }}" class="btn">View Your Wallet</a>
</div>

<div class="highlight-box">
    <strong>Did You Know?</strong><br>
    Reinvesting your dividends can significantly boost your returns through compound growth.
    Consider investing in our latest EV fleet opportunities!
</div>

<p>
    Thank you for being a valued FleetFi investor. Your investment is helping build a
    sustainable transportation future!
</p>

<p>
    Best regards,<br>
    <strong>The FleetFi Finance Team</strong>
</p>
@endsection
